base_url = "https://github.io"
title = "Mechacat"
description = "Personal website"
theme = "terminus"
default_language = "es"
compile_sass = true

[markdown]
[markdown.highlighting]
theme = "github-dark"

[extra]
palette = "monochrome"

# IMPORTANTE: Esto le dice a las plantillas HTML dónde ir a buscar el CSS del tema
styles = [
    "style.css"
]

[[extra.menu.main]]
name = "inicio"
url = "/"
weight = 1