name: Build and deploy Zola website
on:
  push:
    branches:
      - main  # Si tu rama de GitHub se llama "master", cámbialo aquí

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main repository
        uses: actions/checkout@v4

      # FORMA ULTRA SEGURA: GitHub descarga el tema usando sus propias herramientas nativas
      - name: checkout terminus theme
        uses: actions/checkout@v4
        with:
          repository: ebkalderon/terminus
          path: themes/terminus

      # Compilación oficial usando Zola v0.22.1
      - name: Build Zola + upload Pages artifact
        uses: getzola/github-pages@v1
        with:
          zola_version: v0.22.1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4