name: Build and deploy Zola website
on:
  push:
    branches:
      - main  # Si tu rama de tu repositorio de GitHub se llama "master", cámbialo aquí

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # DESCARGA EL ZIP APUNTANDO A LA RAMA MASTER DEL TEMA
      - name: Install Terminus Theme
        run: |
          mkdir -p themes/terminus
          curl -L https://github.com -o theme.zip
          unzip theme.zip
          mv terminus-master/* themes/terminus/
          rm -rf theme.zip terminus-master

      - name: Build Zola + upload Pages artifact
        uses: getzola/github-pages@v1
        with:
          zola_version: v0.22.1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
